### PR TITLE
Replace a selective face throughout the video

### PR DESCRIPTION
**Pull request by maximq**
Implemented face replacement filters by age and gender

https://github.com/s0md3v/roop/assets/43162306/25b02288-7067-4670-a7bf-d626d0911b06

### CODE REVIEW

**Comment by JPW0080** [comment]
Does not agree.

Anaconda3 3.10.6:

Traceback (most recent call last):
  File "C:\various-apps\roop\run.py", line 6, in <module>
    core.run()
  File "C:\various-apps\roop\roop\core.py", line 278, in run
    window = ui.init(
  File "C:\various-apps\roop\roop\ui.py", line 347, in init
    gender_combobox.current(genders.index(roop.globals.gender))
ValueError: None is not in list

**Comment by maximq** [comment]
> Does not agree.
> 
> Anaconda3 3.10.6:
> 
> Traceback (most recent call last): File "C:\various-apps\roop\run.py", line 6, in core.run() File "C:\various-apps\roop\roop\core.py", line 278, in run window = ui.init( File "C:\various-apps\roop\roop\ui.py", line 347, in init gender_combobox.current(genders.index(roop.globals.gender)) ValueError: None is not in list

the error appears if the "--gender" key was not specified – fixed [aa9efba](https://github.com/s0md3v/roop/pull/385/commits/aa9efba0ca74c62ca6fae568605ba3ac5c82c3a9)

**Comment by JPW0080** [comment]
Appears to cooperate but this does show up when inputting value into the Age of face edit fields.

(roop) C:\various-apps\roop>python run.py --gpu-vendor nvidia --keep-frames --keep-fps
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Anaconda3\envs\roop\lib\tkinter\__init__.py", line 570, in get
    return self._tk.getint(value)
_tkinter.TclError: expected integer but got ""

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3\envs\roop\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\various-apps\roop\roop\ui.py", line 355, in <lambda>
    age.trace('w', lambda name, index, mode, age=age: edit_age(age))
  File "C:\various-apps\roop\roop\ui.py", line 164, in edit_age
    if age.get() == 0:
  File "C:\Anaconda3\envs\roop\lib\tkinter\__init__.py", line 572, in get
    return int(self._tk.getdouble(value))
_tkinter.TclError: expected floating-point number but got ""

**Comment by henryruhs** [comment]
Hello, this is wonderful addition. Unfortunately you developed it against the master and not against the next branch (that changed a lot as of refactoring). Do you mind to send a new PR?

1. Please add only 2 arguments as measurement errors are too technical

`--match-age`
`--match-gender`

2. Apply the checkboxes with relative unit (you can make WINDOW_HEIGH larger)
3. Preview does not come with buttons any longer as it generates on the fly
3.1 detect on the fly according to the `match` argument that is enabled

**Comment by maximq** [comment]
@henryruhs Okay, I'll make a new PR
The measurement error is necessary for the correct search for faces, otherwise, when changing the shadows on the face, the age of the face changes slightly

> 3. Apply the checkboxes with relative unit (you can make WINDOW_HEIGH larger)
do you mean the checkbox in the preview window to enable the age detection function?

**Comment by henryruhs** [comment]
> do you mean the checkbox in the preview window to enable the age detection function?

You are right, one is a checkbox - the age matcher should be a `RangeSlider`

**Comment by maximq** [comment]
@henryruhs you can close this PR, I found an opportunity to replace a specific face by comparing the hash of two persons, I will soon make a new PR

**Comment by maximq** [comment]
coming soon

**Comment by henryruhs** [comment]
Looking forward to this!

**Comment by ialhabbal** [comment]
> Implemented face replacement filters by age and gender
> 
>  Selective_face.mp4

How to incorporate/install it in Roop?

**Pull request closed without merging**
