### PR TITLE
Create Ram

### PR DESCRIPTION
**Pull request by banavathsuresh**
Nothing

### CODE REVIEW

**Comment by Patraskon** [comment]
D:\roop-1.3.2>python run.py
Traceback (most recent call last):
  File "D:\roop-1.3.2\run.py", line 6, in <module>
    core.run()
  File "D:\roop-1.3.2\roop\core.py", line 213, in run
    if not frame_processor.pre_check():
  File "D:\roop-1.3.2\roop\processors\frame\face_swapper.py", line 37, in pre_check
    conditional_download(download_directory_path, ['https://huggingface.co/henryruhs/roop/resolve/main/inswapper_128.onnx'])
  File "D:\roop-1.3.2\roop\utilities.py", line 142, in conditional_download
    request = urllib.request.urlopen(url)  # type: ignore[attr-defined]
  File "C:\Program Files\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Program Files\Python310\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

**Comment by jcpsimmons** [comment]
Suggest closing

**Comment by sudip550** [comment]
did anyone find answer for urllib.error.HTTPError: HTTP Error 401: Unauthorized

**Comment by Paresh-Maheshwari** [comment]
> did anyone find answer for urllib.error.HTTPError: HTTP Error 401: Unauthorized

check this [update](https://github.com/s0md3v/roop/pull/862/commits).

**Comment by san5167** [comment]
1、Delete or     # conditional_download(download_directory_path, ['https://huggingface.co/deepinsight/inswapper/resolve/main/inswapper_128.onnx'])
2、Download this file(https://drive.google.com/file/d/1jbDUGrADco9A1MutWjO6d_1dwizh9w9P/view), and put it in the repo /model folder 。

**Pull request closed without merging**
