### PR TITLE
Allow selection of multiple targets (batch process)

### PR DESCRIPTION
**Pull request by kex0**
Select multiple targets including mix of photos and videos and process them all, one by one.

### CODE REVIEW

**Comment by kex0** [comment]
# Video
[IMAGE ALT TEXT HERE](https://www.youtube.com/watch?v=wy4AZ49wOF0)

**Comment by FlowDownTheRiver** [comment]
@kex0 it has a bug,can you fix it? This happens when you select multiple photos for the target,then you start processing,it does the job.But after when you try to select some other amount of pictures or a single picture for the target, it gives this error down below. Also note that replace all faces doesn't replace all faces.Both of these needs to be fixed. And thanks for this feature, it works for multiple pictures but these bugs if you can fix,it will be sweet.

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\roop\roop\roop\ui.py", line 307, in <lambda>
    select_target(select_target_handler, target_path, frames_amount),
  File "C:\roop\roop\roop\ui.py", line 151, in select_target
    analyze_target(select_target_handler, target_path, frames_amount)
  File "C:\roop\roop\roop\ui.py", line 142, in analyze_target
    amount, frame = select_target_handler(target_paths, index)
  File "C:\roop\roop\roop\core.py", line 237, in select_target_handler
    return preview_video(args.target_path[index])
IndexError: tuple index out of range

**Comment by FlowDownTheRiver** [comment]
> I've been trying to keep this uptodate for a week without any word from maintainers. I'm only going to fix it once I know they want this kind of feature.

Thank you very much. I love the feature a lot. This shall be implemented to the main repo because we need it. Having only 1 picture for the elections is very limiting. I have 2 more questions if this is possible, for the preview windows can it be done to support switching to the next and previous pictures with keyboard right arrow key and left arrow key? And if possible when the preview window opens can there be a feature like a check box to apply preview automatically to the current frame or picture without the need of pressing the preview button?

**Comment by FlowDownTheRiver** [comment]
[core.zip](https://github.com/s0md3v/roop/files/11692265/core.zip)
@kex0 I have added a random name generator for the output file for your implementation,cos it was overwriting the output file when the same filename exists. This was a dirty job.It would be better to read the original filenames from target and add a suffix with incremental filename with the protection of checking if still the target folder has a file with the samename,increment it.So it shall cover all cases,but I aam not an advanced programmer,so I did it with the random name solution.

**Comment by henryruhs** [comment]
I close this PR for now - you are free to open a fresh one against the next branch. Thanks for the effort.

**Pull request closed without merging**
