### PR TITLE
Japanese(i18n) support

### PR DESCRIPTION
**Pull request by NaokiSato102**
There exists a bug in cv2.imread/write on the Windows environment related to Japanese paths. Modifications have been made to avoid this issue. Additionally, the Readme has been translated using GPT-4. (This comment has been translated in the same way.)

### CODE REVIEW

**Comment by henryruhs** [comment]
From the CONTRIBUTING.md.

Don't... solve third party issues in our project

**Comment by NaokiSato102** [comment]
Why are you rejecting this commit? Are you prohibiting the use outside of the English-speaking world?

**Comment by NaokiSato102** [comment]
Why are you prohibiting use outside of the English-speaking world? Is it because you are a malevolent racist?

**Comment by phineas-pta** [comment]
your fix isnt the first nor the best, check out #533 for better fix

**Comment by NaokiSato102** [comment]
I went because it was still not fixed. Was I reinventing the wheel? Yet, why isn't it fixed even though there's a better solution available?

**Comment by henryruhs** [comment]
Like I said https://github.com/s0md3v/roop/pull/611#issuecomment-1605689846

**Pull request closed without merging**
