### PR TITLE
Adding package versions

### PR DESCRIPTION
**Pull request by hasanisaeed**
Please specify the package names for which you would like to determine the versions, so that we can avoid any version-related issues in the future.

### CODE REVIEW

**Review by TitasDas — APPROVED** [review]
Looks good to me , someone else please double check and this can be pushed.

**Comment by s0md3v** [comment]
@hasanisaeed will hardcoded versions conflict with other programs that require a different version? I have never done this, sorry.

**Comment by hasanisaeed** [comment]
@s0md3v 
Specifying version codes in the `requirements.txt` file for a Python project is highly recommended. It helps in maintaining the reproducibility of your project by ensuring that the exact versions of the dependencies are used across different environments.

By specifying the version codes, you can prevent unexpected issues that may arise due to incompatible or breaking changes in newer versions of the packages. It also allows for easier collaboration and deployment of your project, as everyone involved will be using the same versions of the dependencies.

All the versions I added are the latest versions of the packages. Therefore, if you have updated a package, according to the above All the versions I added are the latest versions of the packages. Therefore, if you have updated a package, according to the above instructions, you should also update its version in this file., you should also update its version in this file.

**Comment by FurkanGozukara** [comment]
biggest problem of python

Working on tutorial hopefully will show how to install on a venv

**Pull request merged**
