### PR TITLE
Feature/preview for face image and input video

### PR DESCRIPTION
**Pull request by TitasDas**
Added a way to see a preview of the face image and the input video after they have been uploaded. This helps the user to know that their image and video have been successfully uploaded and prevents them from accidentally uploading a corrupt image or video file.

### CODE REVIEW

**Comment by s0md3v** [comment]
Thanks for the PR!

Please remove the `__pycache__` files.

**Comment by TitasDas** [comment]
Done.

**Review by TitasDas — COMMENTED** [review]
Resolve conflicts regarding window size

**Comment by FurkanGozukara** [comment]
can this be merged so i can show in the tutorial video

**Comment by TitasDas** [comment]
This is in sync with the status bar update so far. @s0md3v Tried to keep up with the commits on your main branch so that there are no conflicts or loss of updates that may be being made on the main branch.

**Review by s0md3v — CHANGES_REQUESTED** [review]

**Comment by s0md3v** [comment]
Hey, sorry about merge conflicts!

Just edit the dependency as requested and I will handle the rest.

**Comment by henryruhs** [comment]
[TitasDas](https://github.com/TitasDas) this is a dope addition!

**Review by s0md3v — APPROVED** [review]

**Pull request merged**
