### PR TITLE
Introduce pre_check() and limit_resources()

### PR DESCRIPTION
**Pull request by henryruhs**
This is a draft PR so do not merge without testing. I introduced `pre_check()` where we can check of **CUDA** and **CUDNN** version mismatches. The versions are not final and need more user feedback.

Reference: https://docs.nvidia.com/deeplearning/cudnn/support-matrix/index.html

Users are welcome to use my temporary fork: https://github.com/henryruhs/roop until this PR has been merged.

### CODE REVIEW

**Comment by TitasDas** [comment]
I am currently testing this to see if the versions work. This is actually important my computer just crashed twice while using GPU on a windows system. Thanks for introducing this.

**Comment by henryruhs** [comment]
Added `limit_resources()` that introduces `max-memory` but does not work under Ubuntu. Could someone try this for Windows, probably run the app as administrator.

**Comment by theFroh** [comment]
`resource` is a Linux only package, no?

**Comment by henryruhs** [comment]
True, I updated the fork... now using `win32api` for Windows. Please give it another try.

**Comment by Apatiste** [comment]
> True, I updated the fork... now using `win32api` for Windows. Please give it another try.

I'm having this issue in your fork

 "    assert osp.exists(model_file), 'model_file %s should exist'%model_file
AssertionError: model_file inswapper_128.onnx should exist"

**Comment by henryruhs** [comment]
@Apatiste Does the file exist in the project root?

**Comment by bbecausereasonss** [comment]
Tried your repo in WSL (still CPU only) except now doesnt swap the face lol

**Comment by bbecausereasonss** [comment]
Still only using CPU and never throwing any errors...

frame= 1931 fps=188 q=-0.0 Lsize=N/A time=00:01:04.43 bitrate=N/A speed=6.28x
video:1767326kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]

**Comment by henryruhs** [comment]
Look like offtopic and therfore an installation issue

**Comment by ghltshubh** [comment]
--max-memory flag doesn't work on apple M1 device.

**Pull request merged**
