### PR TITLE
Implementing Batch Processing and Queue Management

### PR DESCRIPTION
**Pull request by Riyooo**
Hi,

I really like your program and just missed the possibility of launching batch processes (I initially used a powershell script for doing that). I have then worked on a new functionality that allows the users to process their tasks in batches and manage their task queues. I hope you will like it :)

The key enhancements include:

### User Interface:

I've added a new section in the User Interface for batch processing. It comprises several elements:
- A frame titled 'Batch Process'.
- Buttons for queuing the current task, batch queuing, clearing the queue, and processing the batch.
- A label displaying the number of tasks in the queue.

### Queue Management:

I chose to use an SQLite database to manage tasks:
- A file named roop.db will be automatically created the first time a the queue functionality is used.
- Given that this uses a persistent DB, you could add multiple items to a queue, close the program and relaunch it later to process the queue.

I've implemented various functions to interact with this database:
- A function db_exists to check if the database exists.
- A function db_init to initialize the database and create a table for tasks if it doesn't exist.
- Functions add_to_queue and batch_queue to add tasks to the queue, either individually or in a batch.
- A function clear_queue to delete tasks from the queue.
- A function update_queue_size to count the number of tasks in the queue and update the queue size display.
- A function process_batch to effectively go through the queue and process all the elements in it.

Note that :
- the batch_queue button activates when a source is selected, and that same source will be used for all the added targets.
- this batch_queue will genrate the output filenames using the target filenames and appending to them '_roop_' plus a datetime string. The user could then process the same videos/images multiples times with different sources without overwriting them.
- clear_queue  and process_batch will only activate if queue is not empty.
- The parameters are also saved to the DB and retrieved when batch processing.

### Batch Processing System:

This last function, process_batch, loops through tasks in the queue. It fetches tasks marked 'In Queue' or 'In Progress' (not completed previously), gets the saved parameters for the video transformation tasks, processes them, and once complete, updates their status to 'Completed'.

### Ideas of future improvements:

- Add the possibility for the user to pause between each task
- Show a table of what is currenlty in the queue with potential interactions (modify filename, delete task)
- Make the user able to change the name/suffix used for generating ouput paths for batch_queue

PS : BTW, I am a novice in python and this is my first time working on a python program so don't hesitate to correct me.

### CODE REVIEW

**Comment by henryruhs** [comment]
This PR clearly violated our CONTRIBUTING.md in multiple points and there has been be rejected.

**Comment by Riyooo** [comment]
Ok, thanks for your time and for the detailed answer.

**Comment by henryruhs** [comment]
We have guidelines, so I don't have to explain myself countless times. If you don't invest 5 minutes to read them, then you have to swallow the pill of getting your 5h+ work rejected.

Anyway, I added your PR to our workshop section: https://github.com/s0md3v/roop/wiki/5.-Workshop#mods

**Comment by Riyooo** [comment]
I don't know why you're being so aggressive.

I wanted this and did it for myself first of all so no pill to swallow, thank you for concern. I just thought of sharing it with your community and that seemed normal to me, cause I very rarely have the opportunity to give back to the open source community. For your information, I did read the contributing.md file and spent more than 6 minutes reading them as well as your open issues, I even thought that this could resolve the issue #282.

No worries anyway, I of course respect the direction you wish to steer this project in and understand that my changes may not align with your vision even if I don't clearly see the issue. My apologies if my contributions seemed presumptuous.

**Comment by henryruhs** [comment]
> I wanted this and did it for myself...

Exactly that is the problem... instant of working on one goal everyone is wasting theirs and my time. This was the 150th something PR in just a couple of weeks...

**Pull request closed without merging**
