### PR TITLE
Batch file processing

### PR DESCRIPTION
**Pull request by kex0**
This allows you to select multiple videos or photos or combination of videos and photos and process them all at once.

You can keep original filenames or set your own name and it will add number suffix to each output.
You can choose to override existing files with same name as the output. (by default it adds number suffix if filename already exists)
You can select which file to preview with the dropdown menu in the preview window.

### CODE REVIEW

**Comment by henryruhs** [comment]
Thanks for the PR but in my opinion "batching" should not be part of this application. You can write your own 10 lines of python code to automate it via the CLI.

**Comment by kex0** [comment]
> How to incorporate/install it in Roop?

just clone this branch

**Comment by FlowDownTheRiver** [comment]
@kex0 Again amazing job.I love your batch processing.It works excellent.Please if you can add 1 more feature,I would really appriciate.I have tried to make it with your old code when there was codeformer as an enhancer,and now with your new code for the "next" branch ,I tried and failed again. 

What I want is to ability to select multiple source images.I was able to enable the selection part.But for the processing it became extremely difficult for me. I want to be able to select multiple source images lets say 5,then when I select multiple targets lets say 3 images (video or image) all source images iterates over all target images. As a result I shall get 15 images in the output folder. 
first person gets into 3 images,second person gets into 3 images,third and so on.

Possibly a nested loop is needed and some more modifications,but I am not able to do it. In my trials,it after I enable multiple source selection in the ui, it gave me no face detection error,cos of multiple paths,it was looking for actual filenames,so I modified again to be able to give filenames with full path from a list including filename+extension,it worked but then I wasn't able to go further.

Please can you do multiple source support as well?

**Comment by kex0** [comment]
@FlowDownTheRiver 
> Please can you do multiple source support as well which can iterate over multiple targets?

done

**Comment by FlowDownTheRiver** [comment]
@kex0 Thank you very much.Lots of code change in very short period of time. This feature is pretty unique. Lots of respect for your contribution to the project.

**Comment by henryruhs** [comment]
I suggest to open a thread on Discord under #workshop for this mods. Thanks guys and keep on modding... :-)

**Comment by FlowDownTheRiver** [comment]
> @FlowDownTheRiver Discord thread: https://ptb.discord.com/channels/1113075793799680003/1122878821650137188

discord link doesn't open.private channel or something? @kex0

**Comment by kex0** [comment]
> > @FlowDownTheRiver Discord thread: https://ptb.discord.com/channels/1113075793799680003/1122878821650137188
> 
> discord link doesn't open.private channel or something? @kex0

are you on the roop discord server? https://discord.gg/F8MVhSNy49

**Pull request closed without merging**
