### PR TITLE
Fix: Audio Synchronization Issue Resolved

### PR DESCRIPTION
**Pull request by xaviviro**
This pull request improves the audio synchronization. Now, the audio aligns perfect with video.

### CODE REVIEW

**Review by spatecon — APPROVED** [review]

**Comment by henryruhs** [comment]
@xaviviro Thanks a lot

**Comment by adithya-s-sekhar** [comment]
CRF only affects video quality. It does not have anything to do with audio. Here it seems passing CRF properly encodes the video instead of muxing it together.
You can add `-c:a aac` to encode audio instead.

Also CRF 32 is way too high. Video quality will be heavily downgraded. Default CRF if you didn't specify any, is 21. And that still looks bad. 

Since it is the final part of joining the frames after swapping, I'd recommend CRF 18. It almost lossless and will be a nice boost to quality.

**Comment by xaviviro** [comment]
When you use a CRF value lower than 32 and merge video frames using ffmpeg, you're noticing a change in duration, which leads to audio desynchronization. This issue can occur due to the differences in the compression applied to the video frames during the encoding process.

Lower CRF values result in higher compression, which can affect the individual frame sizes. If the frames have varying sizes, merging them together can cause a change in the overall duration of the video. This change in duration can then lead to audio desynchronization, where the audio no longer matches the corresponding video frames.

**Comment by xaviviro** [comment]
First, we need to ensure that the duration of the video is the same so that the audio aligns. Then, we can use any audio codec we prefer, such as AAC as you mentioned, or any other.

**Comment by xaviviro** [comment]
You're right, that's the theory. But it works with any of the 20 videos I've tested, all of which are different.

**Pull request merged**
