### PR TITLE
Draft: Replace a selective face throughout the video

### PR DESCRIPTION
**Pull request by maximq**
Added the function of searching for the selected person in the preview, changes in the speed of video processing are not noticeable
the models used are w600k_r50.one, det_10g.onnx (installed together with the insightface libs)

https://github.com/s0md3v/roop/assets/43162306/11cdd1fa-fefb-4f3b-bf99-7219af1368e5

### CODE REVIEW

**Comment by maximq** [comment]
it seems that there is no "det_10g.onnx" model in the test environment

**Comment by JPW0080** [comment]
Unsure of the cause but 30FPS input mp4 video becomes 25FPS output mp4 video.

Launch commands:
python run.py --gpu-vendor nvidia --keep-frames --keep-fps
python run.py --gpu-vendor nvidia

Result:

25FPS video in reduced playback speed, like slow motion.

Command Prompt shows no errors.

**Comment by henryruhs** [comment]
We cannot merge the PR in the current state, so I marked this as a draft - it will double the current codebase and we are not able to maintain that. That being said, I think you need to replace some implementations with third party libs.

Simlar to https://github.com/s0md3v/roop/pull/349

**Comment by JPW0080** [comment]
It appears that anything after commit 957c5ec6ce01812d7e8a48ad4585952b59fa99bc from the next branch introduces the aforementioned 25FPS issue.

**Comment by henryruhs** [comment]
The PR does not follow our CONTRIBUTING guidelines.

**Pull request closed without merging**
