### PR TITLE
Create Ty

### PR DESCRIPTION
**Pull request by Nandumudliar**
Hshenebdvdbbdbdbdngkrkrjjd e ehehene DVD ed

### CODE REVIEW

**Review by Ronkiro — CHANGES_REQUESTED** [review]
Spam? lol

**Comment by arsen-ask** [comment]
bro, I'm done. I spent the whole day but I couldn't install it.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for insightface
Failed to build insightface
ERROR: Could not build wheels for insightface, which is required to install pyproject.toml-based projects

**Comment by MortezaAbolhasaniKhajeh** [comment]
حچطوری میشه دانلودش کرد لطفا راهنمایی بفرمائید ؟
How do you download it? please give me some guidance?

**Review by zagbewd — CHANGES_REQUESTED** [review]
null-4f0ebda4c44d02e0

**Comment by qaz3344** [comment]
怎么安装也没有说啊

**Comment by puke-pai** [comment]
不用用啊

**Pull request closed without merging**
