### PR TITLE
Enable dynamic frame selection for GPU multithreading

### PR DESCRIPTION
**Pull request by fortypercnt**
Before, each thread was assigned some specific frames to process at startup. Now, threads use a shared frame counter to determine the next frame to work on. This can help balance out the work between threads in situations where some frames take more time to process than others.
I made the change only for GPU multithreading. For multiprocessing, inter-process communication of the frame counter variable would be required. All cases still work fine with these code changes though:
For GPU single-threading, the frame counter just iterates through all the frames.
For CPU multi-processing, process_video is called with a subset of frames like before, and each process has its own global frame_counter variable, so each process just iterates through its subset of frames, producing the same behavior as before.

### CODE REVIEW

**Comment by fortypercnt** [comment]
Do you know why CPU mode is using multiprocessing instead of multithreading? I read a bit about the ONNX runtime and it seems the preferred way is using one session and multiple threads. That way we don't have to load the model in memory many times. And it would also make the code shorter/cleaner.
IMO the only reason to use multiprocessing is if the python GIL is not released enough and it slows down execution speed. But in our case the main computational load should be in some backend library that is outside of python and can release the GIL.

**Comment by henryruhs** [comment]
You are asking the right questions. I removed multi-processing a couple of days ago as we have many people facing memory issues. The original author @s0md3v stepped in and reverted this.

To be honest, I never made a performance comparison between CPU-only multi-processing and CPU-only multi-threading.

If we can evaluate that multi-processing is equal or slower, I would be fine removing this again. Could you find some time for profiling and benchmarking?

- Memory consumption
- Overall processing time of a 2 min video

**Comment by fortypercnt** [comment]
I did quite a bit of performance testing and reading about ORT settings, here are my findings:

- Setting os.environ['OMP_NUM_THREADS'] = '1' has no effect. I assume my ORT install is not compiled with OpenMP support. Number of threads for a session should instead be set via sess_options.intra_op_num_threads = ... (https://onnxruntime.ai/docs/performance/tune-performance/threading.html)
- intra_op_num_threads defaults to 0 ("let ORT decide") which is then set to logical cores / 2. So even when using a single thread in roop on CPU, multithreading is used internally, and it can be setup to use however many cores you want, without needing to do your own threading.
- The multi-processing on CPU is buggy: new processes that are spawned each do imports again, which means roop.globals is gonna be executed again including providers = onnxruntime.get_available_providers().  In the new processes, providers are gonna be set to use CUDA if it is available, even if the main process removed CUDA from providers.

```
CPU, using 1 thread (uses #logical_cores/2 internally):
Processing: 100%|██████████| 754/754 [04:43<00:00,  2.66frame/s, mode=cpu, threads=1, memory=16]

CPU, using 8 threads (100% CPU usage, not much extra memory):
Processing: 100%|██████████| 754/754 [03:30<00:00,  3.59frame/s, mode=cpu, threads=8, memory=16]

CPU, using 1 thread and setting intra_op_num_threads = 1 (true single-threading):
Processing:   3%|▎         | 21/754 [01:05<37:24,  3.06s/frame, mode=cpu, threads=1, memory=16]

GPU, using 8 threads:
Processing: 100%|██████████| 754/754 [00:11<00:00, 65.30frame/s, mode=gpu, threads=8, memory=16]

GPU, using 16 threads:
Processing: 100%|██████████| 754/754 [00:11<00:00, 66.79frame/s, mode=gpu, threads=16, memory=16]

multiprocessing CPU with --cpu-cores 2 (uses CUDA due to bug):
Processing: 100%|██████████| 377/377 [00:51<00:00,  7.29frame/s, mode=cpu, cores=None, memory=None]
Processing: 100%|██████████| 377/377 [00:52<00:00,  7.17frame/s, mode=cpu, cores=None, memory=None]

used 20GB ram, lots of CPU AND also lots of GPU and VRAM

after fixing bug by setting providers = ['CPUExecutionProvider'] in globals.py: (100% CPU, takes double memory)
Processing: 100%|██████████| 377/377 [04:18<00:00,  1.46frame/s, mode=cpu, cores=None, memory=None]
Processing: 100%|██████████| 377/377 [04:20<00:00,  1.45frame/s, mode=cpu, cores=None, memory=None]
```

Conclusions:
For GPU, multi-threading approach is good, no need to change.
For CPU, just set intra_op_num_threads (or leave at default 0 to choose logical cores/2). No need for extra threading or even multiprocessing.

**Comment by Mayorc1978** [comment]
> * The multi-processing on CPU is buggy: new processes that are spawned each do imports again, which means roop.globals is gonna be executed again including providers = onnxruntime.get_available_providers().  In the new processes, providers are gonna be set to use CUDA if it is available, even if the main process removed CUDA from providers.

This happens because of this:
```python
def process_frames(source_img, frame_paths, progress=None):
    source_face = get_face_single(cv2.imread(source_img))
```
`process_frames` is the function used by all processes so if you use `get_face_single` inside il will always redo those imports.
Plus the whole logic of using file reads inside the threads is wrong, because it adds unnecessary overhead, `source_face ` can be created outside the loop and passed as a parameter to the thread instead of passing `source_img` as a path.

Same analogy for passing the frames, instead of passing a list of **frame img paths**, just preload the frames in memory outside the loop and pass a list of cv2 images to the threads for processing.

**Comment by henryruhs** [comment]
I close this PR for now as the codebase of next experienced it's final refactoring towards dynamic frame processors.
@fortypercnt Please open a fresh one. Multiprocessing is gone for now

**Pull request closed without merging**
