### PR TITLE
Issue 511 opencv unicode paths

### LINKED ISSUE #511: Problem with non-latin symbols in paths under Windows
Tried on the `next` branch on Windows 11 with Russian locale.
There is a bug when the source or target path contains any non-ASCII symbol. I reproduced it using Cyrillic and Mkhedruli (Georgian alphabet) symbols.
To reproduce the issue, rename any file to `тестовое видео.mp4` (or `ტესტი ვიდეო.mp4` for Mkhedruli) and use it as the target, either in console or GUI mode. As a result, you will receive a bunch of errors, one for every frame: `['NoneType' object has no attribute 'shape'
WARN:3@495.146] global loadsave.cpp:244 cv::findDecoder imread_('D:/WORK/data\temp\╤В╨╡╤Б╤В╨╛╨▓╨╛╨╡ ╨▓╨╕╨┤╨╡╨╛\0355.png'): can't open/read file: check file path/integrity.`
изображение
Additionally, when the source file contains a Cyrillic letter (you can test it with `лицо.png`), you will also encounter an error.
изображение

This bug does not affect the output path names.

I'll try to send a PR to fix it.

### PR DESCRIPTION
**Pull request by pozitronik**
closes #511
There is a [bug in opencv](https://github.com/opencv/opencv/issues/4242) related to Unicode path support under Windows.
It can be avoided using numpy for side loading and saving. This PR does so.

I don't know if it's appropriate to apply this solution because the error is not in the roop code itself, but in a third-party library.

### CODE REVIEW

**Comment by phineas-pta** [comment]
for better maintenance, you should put in a function in `utilities.py`

```python
def read_image(path: str) -> np.array:
    """read an image from a path with Unicode characters"""
    if platform.system().lower() == 'windows':
        return cv2.imdecode(np.fromfile(path, dtype=np.uint8), cv2.IMREAD_UNCHANGED)
    else:
        return cv2.imread(path)
```

**Comment by K1llMan** [comment]
Won't work if direct frames reading will be implemented.

**Comment by K1llMan** [comment]
How target path can be fixed here?
https://github.com/s0md3v/roop/blob/6f65bbe471b156a9489a735dc79bc05600729bae/roop/capturer.py#L6

**Comment by pozitronik** [comment]
> How target path can be fixed here?
> 
> https://github.com/s0md3v/roop/blob/6f65bbe471b156a9489a735dc79bc05600729bae/roop/capturer.py#L6

`cv2.VideoCapture()` somehow works just fine with Unicode paths

**Pull request closed without merging**
