### PR TITLE
very detailed tutorial video

### PR DESCRIPTION
**Pull request by FurkanGozukara**
currently fixing subtitles and adding video chapters. I am also giving 100% support to visitors. I am active already :) I hope you accept this pull request

### CODE REVIEW

**Comment by s0md3v** [comment]
hi @FurkanGozukara, thanks a lot for the tutorial!

However, I can't merge this because our install instructions have shifted to the wiki and I will add it there.

**Comment by henryruhs** [comment]
This is still a fantastic video... thanks a lot, we could add the post processing to the script

**Comment by FurkanGozukara** [comment]
> hi @FurkanGozukara, thanks a lot for the tutorial!
> 
> However, I can't merge this because our install instructions have shifted to the wiki and I added your video there!

Sure thank you so much

**Comment by FurkanGozukara** [comment]
> This is still a fantastic video... thanks a lot, we could add the post processing to the script

Thanks
Yes definitely improves

**Pull request closed without merging**
