### PR TITLE
ADD batch scripts for setup and run on Windows

### PR DESCRIPTION
**Pull request by NRngnl**
The scripts are modified based on [bmaltais/kohya_ss](https://github.com/bmaltais/kohya_ss) 
It will help to create the virtualenv and setup the torch for CPU / Nvidia CUDA.

### CODE REVIEW

**Comment by henryruhs** [comment]
I like the idea but we need this cross-platform, therefore written in python. Can you give it a try? ChatGPT might help.

**Comment by luiscosio** [comment]
It works like a charm, thank you. 

Just missing adding the `venv `folder to the ` .gitignore`

**Comment by luiscosio** [comment]
> I like the idea but we need this cross-platform, therefore written in python. Can you give it a try? ChatGPT might help.

Since this bat script actually installs Python and creates the virtual environment, it makes sense for it to be a script rather than something in Python.

Something like this:

https://github.com/oobabooga/one-click-installers

Having it built in Python would defeat the purspose.

**Comment by NRngnl** [comment]
> I like the idea but we need this cross-platform, therefore written in python. Can you give it a try? ChatGPT might help.

The script is for creating the virtualenv to run Roop.

Therefore it is more make sense to be a batch script.

For cross platform support, I think using another set of bash script like the repository I referenced is more appropriate than using python.

**Pull request closed without merging**
