### PR TITLE
Progress bar for swapper

### PR DESCRIPTION
**Pull request by K1llMan**
Test approach for progress bar for swapper only for now.
image

### CODE REVIEW

**Comment by henryruhs** [comment]
@K1llMan Again this is not a pure PR - it contains tons of other stuff.

**Comment by K1llMan** [comment]
@henryruhs it won't work without events. I can't do features with copy-paste and import all everywhere.

**Comment by henryruhs** [comment]
@K1llMan I don't say you are wrong... not having the event approach will cause circular imports. Still, a PR should be dedicated to one feature or improvement and not come with a bag of them.

**Comment by AlanZhou2022** [comment]
when I swap face in a 1 minute video in my MacBook, Python multi-thread crawler memory continues to grow and the final memory usage reached almost 70 G (including the swap RAM) which sometimes causes the programme to shutdown, that really shocks me, is there any solution for this problem? Thank you very much. (plus: swaping faces in pictures is OK)

**Pull request closed without merging**
