### PR TITLE
Fix processors for images

### PR DESCRIPTION
**Pull request by K1llMan**
Image processors work with same image sources instead continuous update process. Fixed by working with temp directory source.

### CODE REVIEW

**Comment by henryruhs** [comment]
@K1llMan Let's talk about this on Discord. I have my doubts this can work with our final goal to have custom frame processor pipelines.

**Comment by K1llMan** [comment]
Ok. PM me.

**Comment by henryruhs** [comment]
@Moeblack Do you agree, this does not work with the dynamic loaded processor we are planning!?

**Comment by henryruhs** [comment]
In our approach the processors work independent from each other:

```
for processor in processors:
    image = processor.process_image(image)
```

Therefore this PR does fix the issue but not help on long term.

**Pull request closed without merging**
