### PR TITLE
fix: suggest better output filenames

### PR DESCRIPTION
**Pull request by blurymind**
This is a tiny pr that would make a big usability improvement on this thing imo 

Title says it all really.

It's a cool app btw. Had fun putting my face on silly things :)

### CODE REVIEW

**Comment by henryruhs** [comment]
Thanks for the PR, this will not make it into roop. Should be solved in the utilities.py by modifying the existing normalize output path method.

**Comment by blurymind** [comment]
would you like me to do a pr that does it in that way?

**Comment by blurymind** [comment]
here is a followup pr :) https://github.com/s0md3v/roop/pull/786
There was no need to close it, I would have applied review notes

**Comment by blurymind** [comment]
@henryruhs are you sure you dont want a different utils method for this?
normalize_output_path returns a full path, it doesnt do a simple filename :) 

But I am guessing that if I pass it certain parameters, maybe we can make it do a filename

**Comment by henryruhs** [comment]
I'm currently working on the new UI so for me the old UI does have low priority. 

CAn we revisit this after I released it? Gradio works with temp files so it's probably a non-issue then.

**Comment by blurymind** [comment]
oh nice! I didn't know that sorry 

Yes of course, I look forward to the new ui!
Is there a wip branch somewhere? Any ETA when it will be out?

**Comment by henryruhs** [comment]
It will be made available on the next branch soon

**Pull request closed without merging**
