### PR TITLE
customtkinter and events

### PR DESCRIPTION
**Pull request by K1llMan**
Image processors work with same image sources instead continuous update process. Fixed by working with temp directory source.

### CODE REVIEW

**Comment by K1llMan** [comment]
Added event-based status mechanism.

```
@events.change_status
def console_status(message: str) -> None:
    print(message)
```

Default tkinter changed for modern customtkinter.
image

**Comment by henryruhs** [comment]
@K1llMan Please send one PR for each feature... we need smaller PRs to have smaller Code Reviews

**Comment by K1llMan** [comment]
Image process fix moved to #441

**Comment by K1llMan** [comment]
customtkinter #442

**Pull request closed without merging**
